### ISSUE TITLE
PCA on domains frequencies?

### ISSUE THREAD

**Issue by alephreish** [flo-compbio/gopca#8]
I have a dataset that is quite a bit different from the input expected by gopca.

It is a set of draft transcriptomes from several closely related species. For many genes I have InterPro domain annotations which in turn have associated GO-terms. The idea is to analyze the domains which have higher representation in certain clades. My ad hoc approach is to make a PCA on **domain frequencies** (absolute numbers are biased due to the fact that exact gene numbers are unknown): the first component differentiates very well between the expected groupings. I need a test similar to gopca to show which GO-terms are significantly overrepresented based on the loadings for individual domains.

So, instead of a gene expression table I have a list of domain frequencies. Some genes actually have more than one domain annotation which might make fulfillment of some assumptions even harder.

Do you see gopca applicable to this type of data?

**Comment by flo-compbio** [comment]
In general, if you think the principal components capture meaningful 
axes of variation in your data (and you said you think that at least the 
first PC does), I think this approach would work, or would at least be 
worth trying.

If I understand correctly, instead of genes, you have domain frequencies 
(I'm assuming the number of domains is relatively large, let's say 

> 100), and your samples are different species. If the number of species 
> you have is very small (let's say, 5), I would expect that only the 
> first PC would be interesting. GO-PCA implements a method to try to 
> determine the number of PCs automatically, and I hope it would give you 
> an answer of 0 or 1. (You can also specify directly that you want to 
> only look at the first PC, with "-D 1"). If you have more species, say 
> 15-20, then I think looking at additional PCs would also be 
> interesting. But again, try to see what the automatic determination 
> method gives you.

Anyway, you would basically have to generate your own gene set file -- the 
format is described in the docs (http://gopca.readthedocs.io/en/latest/gene_set_files.html) --, which maps GO terms to domains (instead of 
genes). As long as the row identifiers in your "expression matrix" match 
those used in the gene set file, GO-PCA will do the job (whether the 
output will look interesting or not of course also depends on your 
data). Maybe you would want to play around with the X_min, X_frac, and L 
parameters a bit to determine the minimum number of domains in a 
signature etc. In general, if your domains are highly correlated (e.g., 
if there are 20 sub-types of a particular domain family that all map to 
almost exactly the same GO terms), then you want to either try to reduce 
this redundancy in a pre-processing step, or you might want to increase 
X significantly, from 5 (default), to say 20.

Hope that helps. -Florian

**Comment by alephreish** [comment]
Thanks for your input! I'll give it a try.

**Comment by alephreish** [comment]
No, the problem of domain non-independance is a serious obstacle: some of the domains systematically come together and have their respective terms amplified.

**Comment by flo-compbio** [comment]
Yes, that makes sense. Like I said, if this happens a lot (i.e., large "families" of domains), it's not a good idea to ignore that. Not only does this invalidate the enrichment p-values, but the PC loadings will also be affected. So then you would have to do some other pre-processing step to reduce the redundancy. I think small degrees of dependence are not a big problem.
